project_id = "xmfiisxvjrbvnufibgve"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[functions.chat-assistant]
verify_jwt = false
