// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmfiisxvjrbvnufibgve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtZmlpc3h2anJidm51ZmliZ3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMDkwNDUsImV4cCI6MjA3Njc4NTA0NX0.f1x6RcBKE51xPgA-iQXvZCGLO7tPY8HCusTzjtzGmDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});